### ISSUE TITLE
Server Side Encryption

### ISSUE THREAD

**Issue by JonasViewegh** [ArjenLammers/awsservices#5]
Hello,

when the bucket is set up to require server side encryption, it is necessary to edit the java action S3_PutObject.
Would be nice to extend the action with parameter that would be provided for .serverSideEncryption().

Thank you.

Jonas

**Comment by ArjenLammers** [comment]
Hi Jonas,

Do you mean that it is now mandatory to supply this serverSideEncryption, or is it required because you are using a key managed by your own for S3 uploads?
Because I expect this to be transparent on the API unless you want to deviate from it (https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html#aws-managed-customer-managed-keys).

Kind regards,
Arjen Lammers

**Comment by JonasViewegh** [comment]
Hello Arjen,

it is not mandatory to supply. I see that I opened this as an issue and now that I think about it, it is more nice-to-have. A lot of our project require this and that means we need to use extensions, or if the dev are not careful and they change the original action they cannot update from app store.
I don't have enough experience so I don't know if this is common case, but if it is it would be nice to have a parameter.
Nevertheless, thank you for the quick reply! Keep up the good work.

Kind regards

Jonas Viewegh
